### ISSUE TITLE
Switch to JSR-223 embedded host?

### ISSUE THREAD

**Issue by stevefan1999-personal** [DevSrSouza/Bukkript#4]
https://github.com/Kotlin/kotlin-script-examples/blob/74d213e82793c2af7ae31adf4021cac78a149b75/jvm/jsr223/jsr223-simple/src/test/kotlin/org/jetbrains/kotlin/script/examples/jvm/jsr223/simple/test/simpleJsr223Test.kt#L17

It's pretty easy to use, and it will do all the caching and can easily do bindings as well

**Comment by DevSrSouza** [comment]
Is much easier yes! But does not have the much features using the directly Scripting API have!
